multireservoir:
	ifort -check all -traceback definitions.f90 My_variables.f90 rest_subroutines.f90 ffsqp.f qld.f all_simul.f90 multireservoir.f90 -o multireservoir

clean:
	rm -f *.o standard_* *.out *.mod multireservoir
